/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.dynamic.data.mapping.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DDMTrackingCode service. Represents a row in the &quot;DDMTrackingCode&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.dynamic.data.mapping.model.impl.DDMTrackingCodeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.dynamic.data.mapping.model.impl.DDMTrackingCodeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DDMTrackingCode
 * @generated
 */
@ProviderType
public interface DDMTrackingCodeModel
	extends BaseModel<DDMTrackingCode>, CTModel<DDMTrackingCode>, MVCCModel,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ddm tracking code model instance should use the {@link DDMTrackingCode} interface instead.
	 */

	/**
	 * Returns the primary key of this ddm tracking code.
	 *
	 * @return the primary key of this ddm tracking code
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ddm tracking code.
	 *
	 * @param primaryKey the primary key of this ddm tracking code
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this ddm tracking code.
	 *
	 * @return the mvcc version of this ddm tracking code
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this ddm tracking code.
	 *
	 * @param mvccVersion the mvcc version of this ddm tracking code
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this ddm tracking code.
	 *
	 * @return the ct collection ID of this ddm tracking code
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this ddm tracking code.
	 *
	 * @param ctCollectionId the ct collection ID of this ddm tracking code
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the company ID of this ddm tracking code.
	 *
	 * @return the company ID of this ddm tracking code
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ddm tracking code.
	 *
	 * @param companyId the company ID of this ddm tracking code
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the form instance record ID of this ddm tracking code.
	 *
	 * @return the form instance record ID of this ddm tracking code
	 */
	public long getFormInstanceRecordId();

	/**
	 * Sets the form instance record ID of this ddm tracking code.
	 *
	 * @param formInstanceRecordId the form instance record ID of this ddm tracking code
	 */
	public void setFormInstanceRecordId(long formInstanceRecordId);

	/**
	 * Returns the tracking code of this ddm tracking code.
	 *
	 * @return the tracking code of this ddm tracking code
	 */
	@AutoEscape
	public String getTrackingCode();

	/**
	 * Sets the tracking code of this ddm tracking code.
	 *
	 * @param trackingCode the tracking code of this ddm tracking code
	 */
	public void setTrackingCode(String trackingCode);

}