cd /opt/liferay/osgi/marketplace
echo "Remove Unused Apps"
rm -fv 'Liferay CE Collaboration - Liferay CE Connected App - Impl.lpkg'
rm -fv 'Liferay CE Collaboration - Liferay CE Questions - Impl.lpkg'
rm -fv 'Liferay CE Collaboration - Liferay CE Wiki - Impl.lpkg'
rm -fv 'Liferay CE Forms and Workflow - Liferay CE App Builder - API.lpkg'
rm -fv 'Liferay CE Forms and Workflow - Liferay CE App Builder - Impl.lpkg'
rm -fv 'Liferay CE Forms and Workflow - Liferay CE Polls - Impl.lpkg'
rm -fv 'Liferay CE Foundation - Liferay CE Analytics - Impl.lpkg'
rm -fv 'Liferay CE Foundation - Liferay CE Monitoring - Impl.lpkg'
rm -fv 'Liferay CE Collaboration - Liferay CE Blogs - Impl.lpkg'
rm -fv 'Liferay CE Collaboration - Liferay CE Knowledge Base - Impl.lpkg'
rm -fv 'Liferay CE Collaboration - Liferay CE Invite Members - Impl.lpkg'
rm -fv 'Liferay CE Collaboration - Liferay CE Invite Members - API.lpkg'
rm -fv 'Liferay CE Commerce - Liferay CE Commerce - Impl.lpkg'
rm -fv 'Liferay CE Foundation - Liferay CE Dispatch - Impl.lpkg'
rm -fv 'Liferay CE Foundation - Liferay CE Hello World - Impl.lpkg'
rm -fv 'Liferay CE Foundation - Liferay CE License Manager - Impl.lpkg'
rm -fv 'Liferay CE Foundation - Liferay CE Microsoft Translator - Impl.lpkg'
rm -fv 'Liferay CE Foundation - Liferay CE Plugins Admin - Impl.lpkg'
rm -fv 'Liferay CE Foundation - Liferay CE Portal Osgi Debug - Impl.lpkg'
rm -fv 'Liferay CE Foundation - Liferay CE Remote App - API.lpkg'
rm -fv 'Liferay CE Foundation - Liferay CE Remote App - Impl.lpkg'
rm -fv 'Liferay CE Web Experience - Liferay CE Content Dashboard - API.lpkg'
rm -fv 'Liferay CE Web Experience - Liferay CE Content Dashboard - Impl.lpkg'
rm -fv 'Liferay Marketplace - API.lpkg'
rm -fv 'Liferay Marketplace - Impl.lpkg'
rm -fv 'Liferay CE Collaboration - Liferay CE Announcements - API.lpkg'
rm -fv 'Liferay CE Collaboration - Liferay CE Announcements - Impl.lpkg'
